"""Create initial schema for community services platform

Revision ID: 30c1297b48a6
Revises: 
Create Date: 2026-07-28 15:34:54.765944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30c1297b48a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estates',
    sa.Column('estate_id', sa.String(length=36), nullable=False),
    sa.Column('estate_name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('estate_id')
    )
    op.create_table('service_categories',
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('services',
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.category_id'], ),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('resident', 'provider', 'admin', 'security', name='user_role'), nullable=False),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('estate_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['estate_id'], ['estates.estate_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)

    op.create_table('commute_rides',
    sa.Column('ride_id', sa.String(length=36), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=False),
    sa.Column('estate_id', sa.String(length=36), nullable=False),
    sa.Column('from_location', sa.String(length=255), nullable=False),
    sa.Column('to_location', sa.String(length=255), nullable=False),
    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('return_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_seats', sa.Integer(), nullable=False),
    sa.Column('price_per_seat', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('recurrence', sa.Enum('none', 'daily', 'weekly', name='ride_recurrence'), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'cancelled', name='ride_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['estate_id'], ['estates.estate_id'], ),
    sa.PrimaryKeyConstraint('ride_id')
    )
    with op.batch_alter_table('commute_rides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commute_rides_status'), ['status'], unique=False)

    op.create_table('house_listings',
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('estate_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rent_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('bathrooms', sa.Integer(), nullable=False),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('vacant', 'occupied', name='listing_status'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['estate_id'], ['estates.estate_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('listing_id')
    )
    with op.batch_alter_table('house_listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_house_listings_status'), ['status'], unique=False)

    op.create_table('move_requests',
    sa.Column('move_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('pickup_location', sa.String(length=255), nullable=False),
    sa.Column('dropoff_location', sa.String(length=255), nullable=False),
    sa.Column('move_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('service_type', sa.Enum('vehicle', 'loaders', 'packers', 'all', name='move_service_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'assigned', 'in_progress', 'completed', 'cancelled', name='move_status'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('move_id')
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_user_unread', ['user_id', 'is_read'], unique=False)

    op.create_table('service_providers',
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('provider_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_wallets',
    sa.Column('wallet_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('wallet_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('bookings',
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=True),
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('estate_id', sa.String(length=36), nullable=False),
    sa.Column('booking_type', sa.Enum('instant', 'quotation', 'scheduled', name='booking_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'in_progress', 'completed', 'cancelled', name='booking_status'), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['estate_id'], ['estates.estate_id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['service_providers.provider_id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.service_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_status'), ['status'], unique=False)

    op.create_table('ride_bookings',
    sa.Column('ride_booking_id', sa.String(length=36), nullable=False),
    sa.Column('ride_id', sa.String(length=36), nullable=False),
    sa.Column('passenger_id', sa.String(length=36), nullable=False),
    sa.Column('seats_booked', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('booked', 'completed', 'cancelled', name='ride_booking_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['passenger_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['ride_id'], ['commute_rides.ride_id'], ),
    sa.PrimaryKeyConstraint('ride_booking_id'),
    sa.UniqueConstraint('ride_id', 'passenger_id', name='uq_ride_passenger')
    )
    op.create_table('gate_passes',
    sa.Column('gate_pass_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=True),
    sa.Column('visitor_name', sa.String(length=120), nullable=False),
    sa.Column('visitor_phone', sa.String(length=20), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('entry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('qr_code', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', 'used', name='gate_pass_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('gate_pass_id')
    )
    with op.batch_alter_table('gate_passes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gate_passes_qr_code'), ['qr_code'], unique=True)

    op.create_table('payments',
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('mpesa', 'card', 'wallet', 'cash', name='payment_method'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', 'refunded', name='payment_status'), nullable=False),
    sa.Column('transaction_ref', sa.String(length=120), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_transaction_ref'), ['transaction_ref'], unique=True)

    op.create_table('reviews',
    sa.Column('review_id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=False),
    sa.Column('reviewee_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_rating_range'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ),
    sa.ForeignKeyConstraint(['reviewee_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('review_id'),
    sa.UniqueConstraint('booking_id', 'reviewer_id', name='uq_booking_reviewer')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_reviewee_id'), ['reviewee_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_reviewee_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_transaction_ref'))

    op.drop_table('payments')
    with op.batch_alter_table('gate_passes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gate_passes_qr_code'))

    op.drop_table('gate_passes')
    op.drop_table('ride_bookings')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_status'))

    op.drop_table('bookings')
    op.drop_table('user_wallets')
    op.drop_table('service_providers')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_unread')

    op.drop_table('notifications')
    op.drop_table('move_requests')
    with op.batch_alter_table('house_listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_house_listings_status'))

    op.drop_table('house_listings')
    with op.batch_alter_table('commute_rides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commute_rides_status'))

    op.drop_table('commute_rides')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('services')
    op.drop_table('service_categories')
    op.drop_table('estates')
    # ### end Alembic commands ###
