"""add service request, job quote and job status event tables

Revision ID: 411cf0bae049
Revises: 30c1297b48a6
Create Date: 2026-08-05 13:37:50.306972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '411cf0bae049'
down_revision = '30c1297b48a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_requests',
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('resident_id', sa.String(length=36), nullable=False),
    sa.Column('estate_id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=True),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.Enum('instant', 'skilled', name='request_kind'), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('budget_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('budget_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('open', 'quoting', 'assigned', 'completed', 'cancelled', name='request_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.category_id'], ),
    sa.ForeignKeyConstraint(['estate_id'], ['estates.estate_id'], ),
    sa.ForeignKeyConstraint(['resident_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.service_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.create_index('idx_service_requests_estate_status', ['estate_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_requests_resident_id'), ['resident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_requests_status'), ['status'], unique=False)

    op.create_table('job_quotes',
    sa.Column('quote_id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('eta_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'withdrawn', name='quote_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['service_providers.provider_id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['service_requests.request_id'], ),
    sa.PrimaryKeyConstraint('quote_id'),
    sa.UniqueConstraint('request_id', 'provider_id', name='uq_quote_request_provider')
    )
    with op.batch_alter_table('job_quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_quotes_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_quotes_request_id'), ['request_id'], unique=False)

    op.create_table('job_status_events',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('booking_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.Enum('created', 'quoted', 'accepted', 'started', 'completed', 'confirmed', 'cancelled', name='job_event_type'), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['service_requests.request_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('job_status_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_status_events_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_status_events_request_id'), ['request_id'], unique=False)

    # SQLite cannot ALTER a constraint in place, so Alembic runs these through
    # batch mode, which rebuilds the table — and a rebuild needs every
    # constraint to have a name it can re-declare. Autogenerate leaves them as
    # None, so they are named here.
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_id', sa.String(length=36), nullable=True))
        batch_op.create_unique_constraint('uq_bookings_request_id', ['request_id'])
        batch_op.create_foreign_key(
            'fk_bookings_request_id', 'service_requests', ['request_id'], ['request_id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bookings_request_id', type_='foreignkey')
        batch_op.drop_constraint('uq_bookings_request_id', type_='unique')
        batch_op.drop_column('request_id')

    with op.batch_alter_table('job_status_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_status_events_request_id'))
        batch_op.drop_index(batch_op.f('ix_job_status_events_booking_id'))

    op.drop_table('job_status_events')
    with op.batch_alter_table('job_quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_quotes_request_id'))
        batch_op.drop_index(batch_op.f('ix_job_quotes_provider_id'))

    op.drop_table('job_quotes')
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_requests_status'))
        batch_op.drop_index(batch_op.f('ix_service_requests_resident_id'))
        batch_op.drop_index('idx_service_requests_estate_status')

    op.drop_table('service_requests')
    # ### end Alembic commands ###
